language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - pypy
install:
  - pip install pylint -r requirements.txt --allow-external argparse --allow-unverified argparse
script:
  - pylint --errors-only --additional-builtins=raw_input smugline.py
